version: '2.1'
# 6/23/2017 - version 3.x does not support extends yet.
# - https://docs.docker.com/compose/extends/#extending-services
services:
  dashboard:
    build: .
    ports:
      - "3333:3000"
    environment:
      AUTHENTICATION_API_BASE_URL: "https://web.preint02.cwds.io/perry"
    volumes:
      - .:/var/www/dashboard
    tty: true
    stdin_open: true
  redis:
    image: 'redis:3.0'
