version: '3'
services:
  dashboard:
    build: .
    ports:
      - "8888:3000"
    environment:
      - LOGIN_URL=http://localhost:8889/perry # ugg! path is hardcoded in cwds-auth gem
  redis:
    image: 'redis:3.0'
  perry:
    image: cwds/perry
    ports:
      - "8889:8080"
    environment:
      - DEV_MODE=true
