version: '3.5'
services:
  redis:
    image: 'redis:3.0'
  perry:
    image: cwds/perry
    ports:
      - "8889:8080"
    environment:
      - DEV_MODE=true
  dashboard:
    depends_on:
      - redis
    build: .
    ports:
      - "8888:3000"
    env_file:
      - ./.env
    environment:
      # RAILS_ENV: development
      # SKIP_CHECK_YARN_INTEGRITY: 1 # ugg! stupid asset:precompile task clobbers dev deps!
      LOGIN_BASE_URL: http://localhost:8889/perry # ugg! path segment '/authn/login' is hardcoded in cwds-auth gem
      PERRY_BASE_URL: http://perry:8080/perry
      REDIS_HOST: redis
      REDIS_PORT: 6379
