# alskdfj

#
services:
  - name: Snapshot
    id: snapshot
    enabled: true
    roles: []
    summary: >
      Search for people and their past child welfare history by using the Child Welfare History Snapshot tool.
    link:
      text: Child Welfare History Snapshot Tool
      href: https://web.preint.cwds.io/intake
  - name: Hotline
    id: hotline
    enabled: true
    roles: []
    summary: >
      Create child abuse screenings by entering pertinent information/allegations; searching for child welfare history; and determining the level of risk of abuse and/or neglect for assignment.
    link:
      text: Hotline Screener Tool
      href: https://web.preint.cwds.io/intake
  - name: CALS (Facilities)
    id: facilities
    enabled: true
    roles: []
    summary: >
      Search CWS/CMS, LIS and FAS data for Facilities, Children associated to facilities and Facility Complaint History.
    link:
      text: Facility and Home Search and Profile
      href: https://web.preint.cwds.io/cals
  - name: CALS (RFA)
    id: rfa
    enabled: true
    roles: []
    summary: >
      View and create RFA applications for potential applicants looking to provide safe homes for children.
    link:
      text: Resource Family Application
      href: https://web.preint.cwds.io/cals
  - name: Case Management
    id: case-management
    enabled: false
    roles: []
    summary: >
      There once was a man short man from Ealing
    link:
      text: Case Management
      href: https://web.preint.cwds.io/cals

# asldkfjas
resources:
  - name: Training
    id: training
    enabled: true
    roles: []
    summary: >
      Job aids, demo videos and other training tools are available for staff to learn CWS-CARES at their own pace.
    link:
      text: Training
      href: https://cwscms.osi.ca.gov/Portal/Digital-Services-Implementation-Portal/Training?folderId=1957
  - name: Release Notes
    id: release-notes
    enabled: true
    roles: []
    summary: >
      Visit Github to see a log of new features, improvements and bug fixes organized by their release dates.
    link:
      text: Release Notes
      href: https://github.com/ca-cwds/Sandbox/blob/master/Release%20Notes/release_notes.md
